### ISSUE TITLE
more detailed tracking of device 

### ISSUE THREAD

**Issue by Yetispapa** [matomo-org/matomo-sdk-ios#226]
we implemented the matomo iOS sdk in our mobile app for analytics. Everything works greate. We just noticed that in our dashboard we only get "Apple - IPhone" as the device tracked. Now with a deeper look into the code of the matomo SDK I could find source code which reads out all the detailed stuff which we want like this:

```
 static func makeCurrentDevice() ->  Device {
        let platform = currentPlatform()
        let humanReadablePlatformName = humanReadablePlatformNameForCurrentDevice()
        let os = osVersionForCurrentDevice()
        let screenSize = screenSizeForCurrentDevice()
        let nativeScreenSize = nativeScreenSizeForCurrentDevice()
        return Device(platform: platform,
                      humanReadablePlatformName: humanReadablePlatformName,
                      osVersion: os,
                      screenSize: screenSize,
                      nativeScreenSize: nativeScreenSize)
    }
```

but the only information which is taken is screenSize:

```
public struct Event {
..
let screenResolution : CGSize = Device.makeCurrentDevice().screenSize
```

Is there a way to retrieve the detailed device model? So that we can see it in our dashboards.

Thanks in advance

**Comment by brototyp** [comment]
Hi @Yetispapa, thanks for your question. Since that is a frequently asked question, I just added an FAQ page to the wiki [answering your question](https://github.com/matomo-org/matomo-sdk-ios/wiki/FAQ#in-the-backend-devies-are-just-shown-as-apple-iphone-how-do-i-get-more-information-such-as-specific-device-or-os-version). Please try that out.
